version: 2

jobs:
  build:
    branches:
      ignore:
        - master
    machine:
      image: ubuntu-1604:201903-01
      docker_layer_caching: false
    steps:
      - checkout
      - run:
          name: "Check commits of the PR branch"
          command: ./.circleci/check_commits.sh
